'use client';

import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertCircle, BarChart3, Bell, CalendarDays, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, LayoutDashboard, MessageCircle, MoreHorizontal, RefreshCw, Search, Settings, Stethoscope, Users, UserRound, XCircle } from 'lucide-react';

type Section = 'Overview' | 'Leads' | 'Patients' | 'Appointments' | 'Revenue Recovery' | 'Treatment Plans' | 'Analytics' | 'Integrations';
type Data = { clinic?: { name: string; timezone: string; currency: string }; metrics: { revenueRecovered: number; treatmentValueAtRisk: number; missedAppointments: number; followUpsDue: number }; counts: Record<string, number>; leads: any[]; patients: any[]; appointments: any[]; treatmentPlans: any[]; recovery: any[] };
const nav: { label: Section; icon: typeof LayoutDashboard }[] = [
  { label: 'Overview', icon: LayoutDashboard }, { label: 'Leads', icon: Users }, { label: 'Patients', icon: UserRound },
  { label: 'Appointments', icon: CalendarDays }, { label: 'Revenue Recovery', icon: CircleDollarSign }, { label: 'Treatment Plans', icon: Stethoscope }, { label: 'Analytics', icon: BarChart3 }, { label: 'Integrations', icon: Settings },
];
const money = (n: number) => `KES ${Number(n || 0).toLocaleString('en-KE')}`;
const label = (s: string) => (s || '').replaceAll('_', ' ').replace(/\b\w/g, x => x.toUpperCase());

export default function Home() {
  const [section, setSection] = useState<Section>('Overview');
  const [query, setQuery] = useState('');
  const [selected, setSelected] = useState<any | null>(null);
  const [notice, setNotice] = useState('');
  const [data, setData] = useState<Data | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const load = async () => {
    setLoading(true); setError('');
    try { const res = await fetch('/api/dashboard', { cache: 'no-store' }); const json = await res.json(); if (!res.ok || !json.ok) throw new Error(json.error || 'Database unavailable'); setData(json); }
    catch (e) { setError(e instanceof Error ? e.message : 'Database unavailable'); }
    finally { setLoading(false); }
  };
  useEffect(() => { load(); }, []);
  const action = (text: string) => { setNotice(text); setTimeout(() => setNotice(''), 2600); };
  const leads = data?.leads ?? [];
  const filteredLeads = useMemo(() => leads.filter(l => `${l.name} ${l.source} ${l.status}`.toLowerCase().includes(query.toLowerCase())), [leads, query]);
  const clinicName = data?.clinic?.name || 'Dental Clinic';

  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><Activity size={20}/></div><div><strong>Dental<span>Flow</span></strong><small>Revenue Operations</small></div></div>
      <div className="clinic"><div className="clinic-avatar">{clinicName.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><strong>{clinicName}</strong><small>Clinic workspace</small></div><ChevronRight size={15}/></div>
      <nav>{nav.map(({label: n, icon: Icon}) => <button key={n} className={section === n ? 'nav-item active' : 'nav-item'} onClick={() => setSection(n)}><Icon size={18}/><span>{n}</span>{n === 'Revenue Recovery' && (data?.counts.recovery ?? 0) > 0 && <b>{data?.counts.recovery}</b>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="live"><span/> {error ? 'Needs setup' : 'System ready'} <small>{error ? 'Database' : 'Live data'}</small></div><button className="nav-item" onClick={() => setSection('Integrations')}><Settings size={18}/> <span>Settings</span></button></div>
    </aside>
    <section className="content"><header className="topbar"><div><p className="eyebrow">PATIENT OPERATIONS</p><h1>{section}</h1></div><div className="top-actions"><div className="search"><Search size={17}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search patients, leads..."/></div><button className="icon-btn" onClick={() => { load(); action('Data refreshed'); }}><RefreshCw size={18}/></button><button className="icon-btn" onClick={() => action('No new notifications')}><Bell size={18}/><i/></button><div className="avatar">DM</div></div></header>
      {notice && <div className="toast"><CheckCircle2 size={17}/>{notice}</div>}
      {loading && <div className="panel loading-state">Loading clinic data…</div>}
      {!loading && error && <div className="panel error-state"><AlertCircle size={18}/><div><strong>Database connection required</strong><p>{error}</p><button className="primary" onClick={() => setSection('Integrations')}>Open integrations</button></div></div>}
      {!loading && !error && section === 'Overview' && <Overview data={data!} setSection={setSection}/>} 
      {!loading && !error && section === 'Leads' && <LeadsPage leads={filteredLeads} total={leads.length} query={query} setSelected={setSelected} action={action}/>} 
      {!loading && !error && section === 'Patients' && <GenericPage title="Patients" subtitle="Patient profiles, treatment status and communication activity." items={data!.patients.map(p => ({ title:p.full_name, detail:`${p.phone || 'No phone'} · ${label(p.status)}` }))} action={action}/>} 
      {!loading && !error && section === 'Appointments' && <GenericPage title="Appointments" subtitle="Upcoming, completed, cancelled and no-show appointments." items={data!.appointments.map(a => ({ title:new Date(a.scheduled_at).toLocaleString('en-KE',{dateStyle:'medium',timeStyle:'short'}), detail:label(a.status) }))} action={action}/>} 
      {!loading && !error && section === 'Revenue Recovery' && <RecoveryPage rows={data!.recovery} action={action}/>} 
      {!loading && !error && section === 'Treatment Plans' && <GenericPage title="Treatment Plans" subtitle="Track proposed treatment, estimated value and acceptance." items={data!.treatmentPlans.map(p => ({ title:p.treatment_name, detail:`${money(p.estimated_value)} · ${label(p.status)}` }))} action={action}/>} 
      {!loading && !error && section === 'Analytics' && <Analytics data={data!}/>} 
      {!loading && !error && section === 'Integrations' && <Integrations action={action}/>} 
    </section>
    {selected && <div className="overlay" onClick={() => setSelected(null)}><div className="drawer" onClick={e => e.stopPropagation()}><button className="close" onClick={() => setSelected(null)}><XCircle size={20}/></button><div className="profile-head"><div className="large-avatar">{(selected.name || '?').split(' ').map((x:string)=>x[0]).join('')}</div><div><p className="eyebrow">LEAD PROFILE</p><h2>{selected.name}</h2><span>{selected.source || 'Unknown source'} · {label(selected.status)}</span></div></div><div className="detail-grid"><div><small>Estimated treatment</small><strong>{money(selected.estimated_value)}</strong></div><div><small>Next follow-up</small><strong>{selected.follow_up_at ? new Date(selected.follow_up_at).toLocaleDateString('en-KE') : 'Not scheduled'}</strong></div></div><div className="activity"><h3>Activity</h3><div><MessageCircle size={17}/><span>Lead record loaded from database<small>{selected.created_at ? new Date(selected.created_at).toLocaleString('en-KE') : 'Current record'}</small></span></div></div><button className="primary" onClick={() => action('Follow-up task queued')}>Queue follow-up</button></div></div>}
  </main>;
}

function Overview({data,setSection}:{data:Data;setSection:(s:Section)=>void}) { const m=data.metrics; const total=data.counts.leads || 0; const appointments=data.counts.appointments || 0; const plans=data.counts.treatmentPlans || 0; const recovery=data.recovery.slice(0,5); return <>
  <div className="demo-banner"><AlertCircle size={17}/><div><strong>{data.clinic?.name} connected</strong><span>Dashboard metrics and records are being read from the configured database.</span></div><button onClick={()=>setSection('Integrations')}>Manage integrations <ChevronRight size={15}/></button></div>
  <div className="metrics"><Metric title="Revenue recovered" value={money(m.revenueRecovered)} delta="Live" icon={<CircleDollarSign/>}/><Metric title="Treatment value at risk" value={money(m.treatmentValueAtRisk)} delta={`${data.counts.recovery} opportunities`} icon={<AlertCircle/>} risk/><Metric title="Missed appointments" value={String(m.missedAppointments)} delta={`${appointments} total`} icon={<CalendarDays/>}/><Metric title="Follow-ups due" value={String(m.followUpsDue)} delta="Live queue" icon={<Clock3/>} risk/></div>
  <div className="grid-main"><div className="panel"><PanelTitle title="Revenue recovery pipeline" action="View recovery" onClick={()=>setSection('Revenue Recovery')}/><div className="pipeline"><Stage label="Open" value={money(recovery.filter(r=>r.status==='open').reduce((s,r)=>s+Number(r.value_at_risk||0),0))} count={String(recovery.filter(r=>r.status==='open').length)}/><Stage label="Contacted" value={money(recovery.filter(r=>r.status==='contacted').reduce((s,r)=>s+Number(r.value_at_risk||0),0))} count={String(recovery.filter(r=>r.status==='contacted').length)}/><Stage label="Engaged" value={money(recovery.filter(r=>r.status==='engaged').reduce((s,r)=>s+Number(r.value_at_risk||0),0))} count={String(recovery.filter(r=>r.status==='engaged').length)}/><Stage label="Recovered" value={money(m.revenueRecovered)} count={String(recovery.filter(r=>r.status==='recovered').length)} last/></div></div><div className="panel"><PanelTitle title="Data snapshot" action="Analytics" onClick={()=>setSection('Analytics')}/><div className="bars"><Bar label="Leads" value={total ? Math.min(100, Math.round((data.counts.leads/Math.max(total,1))*100)) : 0}/><Bar label="Appointments" value={total ? Math.round((appointments/total)*100) : 0}/><Bar label="Treatment plans" value={appointments ? Math.round((plans/appointments)*100) : 0}/><Bar label="Recovery queue" value={data.counts.recovery ? Math.min(100, data.counts.recovery*10) : 0}/></div></div></div>
  <div className="panel"><PanelTitle title="Priority recovery opportunities" action="View all" onClick={()=>setSection('Revenue Recovery')}/><RecoveryRows rows={recovery}/></div>
 </> }
function LeadsPage({leads,total,setSelected,action}:{leads:any[];total:number;query:string;setSelected:(x:any)=>void;action:(s:string)=>void}) { return <div className="panel page-panel"><PanelTitle title="Lead pipeline" action="+ New lead" onClick={()=>action('Lead creation will be connected to the write API next')}/><div className="filters"><div className="filter active">All <b>{total}</b></div><div className="filter">New <b>{leads.filter(l=>l.status==='new').length}</b></div><div className="filter">Contacted <b>{leads.filter(l=>l.status==='contacted').length}</b></div><div className="filter">Appointment <b>{leads.filter(l=>l.status==='appointment').length}</b></div></div><div className="table"><div className="tr th"><span>Lead</span><span>Source</span><span>Status</span><span>Est. value</span><span>Follow-up</span><span/></div>{leads.map(l=><button className="tr row" key={l.id} onClick={()=>setSelected(l)}><span><strong>{l.name}</strong><small>Patient enquiry</small></span><span>{l.source || '—'}</span><span><em className={l.status==='no_response'?'pill red':'pill'}>{label(l.status)}</em></span><span>{money(l.estimated_value)}</span><span>{l.follow_up_at ? new Date(l.follow_up_at).toLocaleDateString('en-KE') : '—'}</span><ChevronRight size={16}/></button>)}</div>{!leads.length && <Empty text="No leads match this search."/>}</div> }
function RecoveryPage({rows,action}:{rows:any[];action:(s:string)=>void}) { return <div className="panel page-panel"><PanelTitle title="Recovery queue" action="Create task" onClick={()=>action('Recovery task write endpoint is next')}/><RecoveryRows rows={rows} action={action}/>{!rows.length&&<Empty text="No recovery opportunities yet."/>}</div> }
function RecoveryRows({rows,action=()=>{}}:{rows:any[];action?:(s:string)=>void}) { return <div className="table">{rows.map((r,i)=><div className="tr row" key={r.id || i}><span><strong>{label(r.type)}</strong><small>{r.patient_id ? `Patient ${r.patient_id.slice(0,8)}` : 'Unlinked patient'}</small></span><span><em className={r.priority==='high'?'pill red':'pill amber'}>{label(r.priority)}</em></span><span><strong>{money(r.value_at_risk)}</strong></span><span>{r.assigned_to || 'Unassigned'}</span><button className="small-action" onClick={()=>action(`Recovery task for ${label(r.type)} queued`)}>Recover</button><MoreHorizontal size={18}/></div>)}</div> }
function GenericPage({title,subtitle,items,action}:{title:string;subtitle:string;items:{title:string;detail:string}[];action:(s:string)=>void}) { return <div className="panel page-panel"><div className="panel-title"><div><h2>{title}</h2><p>{subtitle}</p></div><button onClick={()=>action(`${title} creation will be connected to the write API next`)}>+ Add</button></div><div className="list">{items.map((x,i)=><div className="list-row" key={`${x.title}-${i}`}><div className="large-avatar small">{String(i+1).padStart(2,'0')}</div><div><strong>{x.title}</strong><small>{x.detail}</small></div><span className="pill">Active</span><button onClick={()=>action(`${x.title} opened`)}>Open <ChevronRight size={15}/></button></div>)}</div>{!items.length&&<Empty text={`No ${title.toLowerCase()} records yet.`}/>}</div> }
function Analytics({data}:{data:Data}) { const total=data.counts.leads||0, ap=data.counts.appointments||0, plans=data.counts.treatmentPlans||0; return <div className="analytics-grid"><div className="panel"><PanelTitle title="Funnel performance" action="Live database" onClick={()=>{}}/><div className="funnel"><div style={{width:'100%'}}>{total} <span>Leads</span></div><div style={{width:`${total?Math.min(100,ap/total*100):0}%`}}>{ap} <span>Appointments</span></div><div style={{width:`${ap?Math.min(100,plans/ap*100):0}%`}}>{plans} <span>Treatment plans</span></div><div style={{width:`${plans?Math.min(100,data.metrics.revenueRecovered/(data.metrics.treatmentValueAtRisk+data.metrics.revenueRecovered)*100):0}%`}}>{money(data.metrics.revenueRecovered)} <span>Recovered</span></div></div></div><div className="panel"><PanelTitle title="Revenue metrics" action="KES" onClick={()=>{}}/><div className="metric-list"><p>Revenue recovered <strong>{money(data.metrics.revenueRecovered)}</strong></p><p>Revenue at risk <strong>{money(data.metrics.treatmentValueAtRisk)}</strong></p><p>Recovery opportunities <strong>{data.counts.recovery}</strong></p><p>Patients <strong>{data.counts.patients}</strong></p></div></div></div> }
function Integrations({action}:{action:(s:string)=>void}) { const items=[['n8n','Workflow automation','Ready to connect'],['WhatsApp','Patient messaging','Not connected'],['Calendar','Appointment scheduling','Not connected'],['CRM / data source','Patient & lead data','Database active'],['AI provider','Follow-up drafting','Not connected']]; return <div className="integration-list">{items.map(x=><div className="integration" key={x[0]}><div className="integration-icon"><Activity size={20}/></div><div><strong>{x[0]}</strong><small>{x[1]}</small></div><span>{x[2]}</span><button onClick={()=>action(`${x[0]} integration settings opened`)}>Configure <ChevronRight size={15}/></button></div>)}</div> }
function Empty({text}:{text:string}) { return <div className="empty-state">{text}</div> }
function Metric({title,value,delta,icon,risk=false}:{title:string;value:string;delta:string;icon:React.ReactNode;risk?:boolean}) { return <div className="metric"><div className="metric-top"><div className={risk?'metric-icon risk':'metric-icon'}>{icon}</div><span className={risk?'delta risk-text':'delta'}>{delta}</span></div><small>{title}</small><strong>{value}</strong></div> }
function PanelTitle({title,action,onClick}:{title:string;action:string;onClick:()=>void}) { return <div className="panel-title"><div><h2>{title}</h2></div><button onClick={onClick}>{action}<ChevronRight size={15}/></button></div> }
function Stage({label: l,value,count,last=false}:{label:string;value:string;count:string;last?:boolean}) { return <div className="stage"><div className="stage-dot"><span/></div><div><small>{l}</small><strong>{value}</strong><span>{count} opportunities</span></div>{!last&&<div className="stage-line"/>}</div> }
function Bar({label:l,value}:{label:string;value:number}) { return <div className="bar-row"><div><span>{l}</span><strong>{value}%</strong></div><div className="bar-track"><i style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div></div> }
